credentials:
  usernames:
    jsmith:
      email: test1@gmail.com
      name: John Smith
      password: $2b$12$w1GMnANUf5uSL9txOgl.XOMNRewvbkUJ4zUZqVsxOHSG/RTNw2Cxu
    rbriggs:
      email: test2@gmail.com
      name: Test2
      password: $2b$12$HsLjEiIXo0jSehKfGNfNiOXRezGdYI3PLVz10QhHk1M7NNX.44KYW
cookie:
  expiry_days: 0
  key: quickf_sign # Must be string
  name: quickf_cookie
preauthorized:
  emails: melsby@gmail.com